[versions]
applicationId = "br.com.asoncsts.multi.gymtrack"
applicationVersion = "1.0.1" # Just one digit each
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

agp = "8.12.0"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.8.3"
androidx-navigation = "2.8.0-alpha10"
coil3 = "3.3.0"
compose-hot-reload = "1.0.0-beta05"
compose-multiplatform = "1.8.2"
firebase-appdistribution = "5.0.0"
firebase-crashlytics = "3.0.2"
firebase-ui = "8.0.2"
google-id = "1.1.1"
google-services = "4.4.2"
koin = "4.0.0-RC2"
kotlin = "2.2.10"
kotlinx-coroutines = "1.10.2"
ksp = "2.2.0-2.0.2"
ktor = "3.2.3"
room = "2.7.2"
sqlite = "2.5.2"

test-junit = "4.13.2"

#agp = "8.7.3"
#androidx-core = "1.16.0"
#androidx-testExt = "1.2.1"
#kotlin = "2.2.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version = "3.0.0-alpha08" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = "com.google.firebase:firebase-bom:33.7.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-ui = { group = "com.firebaseui", name = "firebase-ui-auth", version.ref = "firebase-ui" }
google-id = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-id" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktor-apache5 = { group = "io.ktor", name = "ktor-client-apache5", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-utils = { group = "io.ktor", name = "ktor-utils", version.ref = "ktor" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

test-junit = { group = "junit", name = "junit", version.ref = "test-junit" }

#kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
#androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
#androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidxRoom = { id = "androidx.room", version.ref = "room" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
firebaseAppdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
