name: Build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Set up JDK 11"
      uses: actions/setup-java@v4.6.0
      with:
        java-version: "17"
        distribution: "jetbrains"
        cache: gradle

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew

    - name: "Generate Build Config"
      run: ./gradlew buildConfigGenerator

    - name: "Run all tests"
      run: ./gradlew :composeApp:cleanDesktopTest :composeApp:desktopTest --tests "br.com.asoncsts.multi.gymtrack.*"

    - name: "Build with Gradle"
      run: ./gradlew :composeApp:bundleRelease
