name: Build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up JDK 17"
        uses: actions/setup-java@v4.6.0
        with:
          java-version: "17"
          distribution: "jetbrains"
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Generate Protected Files"
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          UPLOAD_JKS: ${{ secrets.UPLOAD_JKS }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./composeApp/src/google-services.json
          echo $KEYSTORE_PROPERTIES | base64 -di > ./keystore/keystore.properties
          echo $UPLOAD_JKS | base64 -di > ./keystore/upload.jks

      - name: "Generate Build Config"
        run: ./gradlew buildConfigGenerator

      - name: "Run all tests"
        run: ./gradlew :composeApp:cleanDesktopTest :composeApp:desktopTest --tests "br.com.asoncsts.multi.gymtrack.*"

      - name: "Build with Gradle"
        run: ./gradlew :composeApp:bundleRelease

      - name: "Upload app bundle as a artifact"
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "./composeApp/build/outputs/bundle/release/app-release.aab"

      - run: echo "Build status report=${{ job.status }}"
