name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download app bundle"
        uses: actions/download-artifact@v4
        with:
          name: app-bundle

      - name: "Publish to Play Store"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICES_ACCOUNT_JSON }}
          packageName: br.com.asoncsts.multi.gymtrack
          releaseFiles: "${{ github.workspace }}/composeApp-release.aab"
          track: production
