name: Test ADM CI

on:
  workflow_dispatch:
    inputs:
      gradleTask:
        description: "\"./gradlew \" task to build apk, eg: \"app:packageDevApi28DebugUniversalApk\""
        required: true
        type: string
      apkName:
        description: "Upload apk name, eg: \"DEV_DeviceControl_v.2.0.77.9_1295_debug\""
        required: true
        type: string
      apkPath:
        description: "Built apk path, eg: \"./app/build/outputs/apk_from_bundle/devApi28Debug/app-dev-api28-debug-universal.apk\""
        required: true
        type: string
      filesBoxcontrolPath:
        description: "Path after \"adm-team\", eg: \"test-ci/dev/api-28/debug\""
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Check Parameters"
        if: ${{ inputs.gradleTask == '' || inputs.apkName == '' || inputs.apkPath == '' || inputs.filesBoxcontrolPath == '' }}
        run: |
          echo "gradleTask: ${{ inputs.gradleTask }}"
          echo "nameApk: ${{ inputs.apkName }}"
          echo "pathApk: ${{ inputs.apkPath }}"
          echo "pathFilesBoxcontrol: ${{ inputs.filesBoxcontrolPath }}"
          exit 1

      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4.6.0
        with:
          java-version: "17"
          distribution: "jetbrains"
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run:
          chmod +x gradlew

      - name: "Build with Gradle"
        run:
          ./gradlew ${{ inputs.gradleTask }}

      - name: "Publish on files.boxcontrol.io"
        env:
          USER_NAME: ${{ secrets.ADM_FILES_BOXCONTROL_USER_NAME }}
          USER_NAME_URL: ${{ secrets.ADM_FILES_BOXCONTROL_USER_NAME_URL }}
          USER_PASSWORD: ${{ secrets.ADM_FILES_BOXCONTROL_USER_PASSWORD }}
        run:
          curl -u "${USER_NAME}":"${USER_PASSWORD}" -T "${{ inputs.apkPath }}" "https://files.boxcontrol.io/remote.php/dav/files/${USER_NAME_URL}/adm-team/${{ inputs.filesBoxcontrolPath }}/${{ inputs.apkName }}.apk"
