name: Test ADM CI

on:
  push:
    branches: [ "test-adm" ]

#{"gradleTask":"app:packageDevApi28DebugUniversalApk","pathApk":"./app/build/outputs/apk_from_bundle/devApi28Debug/app-dev-api28-debug-universal.apk","pathFilesBoxcontrol":"test-ci/devApi28Debug"}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: echo
        env:
          commitMessage: ${{ fromJSON(github.event.head_commit.message) }}
        run: |
          echo "${{ env.commitMessage.gradleTask }}"
