name: Test ADM CI

on:
  push:
    branches: [ "test-adm" ]

#{"gradleTask":"app:packageDevApi28DebugUniversalApk","pathApk":"./app/build/outputs/apk_from_bundle/devApi28Debug/app-dev-api28-debug-universal.apk","pathFilesBoxcontrol":"test-ci/devApi28Debug"}
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      gradleTask: ${{ fromJSON(github.event.head_commit.message).gradleTask }}
      pathApk: ${{ fromJSON(github.event.head_commit.message).pathApk }}
      pathFilesBoxcontrol: ${{ fromJSON(github.event.head_commit.message).pathFilesBoxcontrol }}
      test: ${{ fromJSON(github.event.head_commit.message).test }}

    steps:
      - name: "Check Parameters"
        if: ${{ env.gradleTask == '' || env.pathApk == '' || env.pathFilesBoxcontrol == '' || env.test == '' }}
        run: |
          echo "gradleTask: $gradleTask"
          echo "pathApk: $pathApk"
          echo "pathFilesBoxcontrol: $pathFilesBoxcontrol"
          echo "test: $test"
          exit 1
