name: Test ADM CI

on:
  push:
    branches: [ "test-adm" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      gradleTask: ''

    steps:
      - name: devApi28Debug
        if: ${{ contains(github.event.head_commit.message, 'devApi28Debug') }}
        run: |
          echo "gradleTask=packageDevApi28DebugUniversalApk" >> $GITHUB_ENV

      - name: devApi30Debug
        if: ${{ contains(github.event.head_commit.message, 'devApi30Debug') }}
        run: |
          echo "gradleTask=packageDevApi30DebugUniversalApk" >> $GITHUB_ENV

      - name: echo
        env:
          commitMessage: ${{ github.event.head_commit.message }}
        run: |
          echo $gradleTask
          echo $gradleTask

      - name: stopJob
        if: gradleTask == ''
        run: |
          exit 1

#      - uses: actions/checkout@v4
#      - name: set up JDK 17
#        uses: actions/setup-java@v4.6.0
#        with:
#          java-version: '17'
#          distribution: 'jetbrains'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run:
#          chmod +x gradlew
#
#      - name: Create google-services.json file
#        env:
#          GOOGLE_SERVICES_JSON: ${{ secrets.ADM_GOOGLE_SERVICES_JSON }}
#        run:
#          echo $GOOGLE_SERVICES_JSON > ./composeApp/src/google-services.json
#
#      - name: Generate BuildConfigGenerator
#        run:
#          ./gradlew buildConfigGenerator
#
#      - name: Build with Gradle
#        run:
#          ./gradlew :composeApp:packageDebug
#
#      - name: Publish on files.boxcontrol.io
#        env:
#          APK_NAME: composeApp-debug
#          APK_PATH: ./composeApp/build/outputs/apk/debug/composeApp-debug.apk
#          USER_NAME: ${{ secrets.ADM_FILES_BOXCONTROL_USER_NAME }}
#          USER_NAME_URL: ${{ secrets.ADM_FILES_BOXCONTROL_USER_NAME_URL }}
#          USER_PASSWORD: ${{ secrets.ADM_FILES_BOXCONTROL_USER_PASSWORD }}
#        run:
#          curl -u "${USER_NAME}":"${USER_PASSWORD}" -T "${APK_PATH}" "https://files.boxcontrol.io/remote.php/dav/files/${USER_NAME_URL}/adm-team/test-ci/${APK_NAME}.apk"
